sudo : required
services:
  - docker

before_install:
  - docker build -t shubhangikumbhar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shubhangikumbhar/react-test npm test -- --coverage 
  
after_success:
  - docker build -t shubhangidocker1/multi-client ./client
  - docker build -t shubhangidocker1/multi-nginx ./nginx
  - docker build -t shubhangidocker1/multi-server ./server
  - docker build -t shubhangidocker1/multi-worker ./worker
#Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shubhangidocker1/multi-client 
  - docker push shubhangidocker1/multi-nginx
  - docker push shubhangidocker1/multi-server
  - docker push shubhangidocker1/multi-worker



